package tops.dw.app;

import java.awt.*;
import java.awt.event.*;

public class AppInfoFrame extends Frame implements ActionListener {

    int WIDTH = 550, HEIGHT = 300;

    Button Dismissbutton;

    AppInfoFrame(String Message) {

        super("Database search information");

        this.setFont(new Font("TimesRoman", Font.PLAIN, Topol.LargeFontSize));

        this.add("Center", new TextArea(Message, 5, 10));

        this.Dismissbutton = new Button("Dismiss");
        this.Dismissbutton.addActionListener(this);

        this.add("South", this.Dismissbutton);

        this.setSize(this.WIDTH, this.HEIGHT);

        this.pack();

    }

    @Override
    public Dimension getPreferredSize() {
        return new Dimension(this.WIDTH, this.HEIGHT);
    }

    /* the action listener interface */
    /*
     * objects of this class only listen for action events generated by the
     * DismissButton
     */
    public void actionPerformed(ActionEvent e) {
        this.dispose();
    }

}
