package tops.dw.app;

import java.applet.*;
import java.awt.*;
import java.awt.event.*;
import java.util.*;
import java.io.*;

import tops.dw.editor.PostscriptPrinter;
import tops.dw.editor.TopsEditor;
import tops.dw.protein.*;

import java.net.*;

/**
 * the applet to use for viewing diagrams generated by the server
 * 
 * @author David Westhead
 * @version 1.00 07 Oct. 1997
 */
public class ResultsApp extends Applet implements ActionListener,
        PostscriptPrinter {

    /* START class variables */

    static final int LargeFontSize = 12;

    static final int SmallFontSize = 12;

    static final String EditorHelpFile = "EditorHelp11.html";

    static final String TopsFileURLbase = "http://www.bioinformatics.leeds.ac.uk/tops_server_files/TOPS";

    private static String cgi_prog_path = "http://www.bioinformatics.leeds.ac.uk/tops.dw.cgi-bin/tops/";

    private static final String cgi_ps_print_prog = "TOPS_PS_Print.cgi";

    /* END class variables */

    /* START instance variables */

    private TextField DiagIdInput = null;

    private TextField MagicInput = null;

    private TextArea ErrorTextArea = null;

    private String diag_id = null;

    private String magic = null;

    private URL EdHelpURL = null;

    private TopsEditor editor = null;

    private String host;

    private int port;

    /* END instance variables */

    @Override
    public void init() {

        this.setFont(new Font("TimesRoman", Font.BOLD, ResultsApp.LargeFontSize));
        this.setLayout(new GridLayout(1, 2));
        this.setBackground(Color.white);

        Panel p = new Panel();
        p.setLayout(new GridLayout(5, 1));
        p.setBackground(Color.white);
        Label l = new Label("Enter your four letter diagram identifier:");
        l.setAlignment(Label.LEFT);
        p.add(l);

        this.DiagIdInput = new TextField(20);
        this.DiagIdInput.setEditable(true);
        p.add(this.DiagIdInput);

        l = new Label("Enter your magic number:");
        l.setAlignment(Label.LEFT);
        p.add(l);

        this.MagicInput = new TextField(20);
        this.MagicInput.setEditable(true);
        p.add(this.MagicInput);

        Button viewb = new Button("View cartoon");
        p.add(viewb);
        viewb.addActionListener(this);

        this.add(p);

        this.ErrorTextArea = new TextArea("Messages from the Tops Server\n");
        this.ErrorTextArea.setEditable(false);

        this.add(this.ErrorTextArea);

        /* set up host and port */
        URL DocBase = this.getDocumentBase();
        this.host = DocBase.getHost();
        this.port = DocBase.getPort();
        if (this.port <= 0)
            this.port = 80;

        String dcb_file = DocBase.getFile();
        StringBuffer path = new StringBuffer();

        boolean copy;
        int i;
        for (i = (dcb_file.length() - 1), copy = false; i >= 0; i--) {
            if (dcb_file.charAt(i) == '/')
                copy = true;
            if (copy) {
                path.insert(0, dcb_file.charAt(i));
            }
        }

        try {
            this.EdHelpURL = new URL("http", this.host, this.port, path.toString()
                    + ResultsApp.EditorHelpFile);
        } catch (MalformedURLException mue) {
            this.EdHelpURL = null;
        }

    }

    @Override
    public void stop() {

        // just dispose of any windows created
        if (this.editor == null)
            return;
        this.editor.quit();
        this.editor = null;
        return;

    }

    @Override
    public void destroy() {

        // just dispose of any windows created
        if (this.editor == null)
            return;
        this.editor.quit();
        this.editor = null;
        return;

    }

    /* this class only listens for action events from the magic input field */
    public void actionPerformed(ActionEvent e) {

        this.diag_id = this.DiagIdInput.getText().trim();
        this.magic = this.MagicInput.getText().trim();

        if (this.editor != null) {
            this.editor.quit();
            this.editor = null;
        }

        String status = null;

        try {
            status = this.getTOPSstatus(this.diag_id, this.magic);
        } catch (MalformedURLException mue) {
            this.ErrorTextArea.append("There is a problem with the status URL.\n");
            this.ErrorTextArea
                    .append("This may be a server bug, please contact the administrator.\n");
            return;
        } catch (IOException ioe) {
            this.ErrorTextArea
                    .append("There is a problem reading your cartoon status.\n");
            this.ErrorTextArea.append("Your magic number may be wrong.\n");
            return;
        }

        if (status == null) {
            this.ErrorTextArea
                    .append("There is a problem reading your cartoon status.\n");
            this.ErrorTextArea.append("Your magic number may be wrong.\n");
            return;
        }

        Protein p = null;
        if (status.equals("Successful")) {
            try {
                p = this.getTOPSdiag(this.diag_id, this.magic);
            } catch (MalformedURLException mue) {
                this.ErrorTextArea
                        .append("There is a problem with the calculated cartoon URL.\n");
                this.ErrorTextArea
                        .append("This may be a server bug, please contact the administrator.\n");
                return;
            } catch (IOException ioe) {
                this.ErrorTextArea
                        .append("There is a problem reading your cartoon.\n");
                this.ErrorTextArea
                        .append("Your cartoon identifier might not match your magic number.\n");
                return;
            }

            if (p != null) {
                this.ErrorTextArea.append("Cartoon found!\n");
                this.ErrorTextArea.append("Setting up viewer and editor!\n");
                this.editor = new TopsEditor(this, this.EdHelpURL);
                this.editor.addProtein(p);
            } else {
                this.ErrorTextArea
                        .append("There is a problem reading your cartoon.\n");
                this.ErrorTextArea
                        .append("Your cartoon identifier might not match your magic number.\n");
                return;
            }
        } else if (status.equals("Processing")) {
            this.ErrorTextArea.append("Your cartoon is not yet ready.\n");
            this.ErrorTextArea.append("Please try again later.\n");
            return;
        } else {
            this.ErrorTextArea.append("Your cartoon generation failed.\n");
            this.ErrorTextArea.append("Please check the format of your PDB file.\n");
            this.ErrorTextArea.append("If the format is OK, then contact us.\n");
            return;
        }

    }

    public void printPostscript(Vector ps) {

        StringBuffer urlbase = new StringBuffer(ResultsApp.TopsFileURLbase);
        urlbase.append(this.magic);
        urlbase.append("/");
        urlbase.append(this.diag_id);

        AppletPSPrinter apsp = new AppletPSPrinter(ps, this.host, this.port,
                ResultsApp.cgi_prog_path, ResultsApp.cgi_ps_print_prog, urlbase.toString());

        try {
            apsp.doPrint();
            urlbase.append(".pdf");
            URL printURL = new URL(urlbase.toString());
            this.getAppletContext().showDocument(printURL, "_blank");
        } catch (IOException ioe) {
            this.ErrorTextArea.append("Error encoutered while trying to print\n");
            this.ErrorTextArea.append(ioe.getMessage());
            this.ErrorTextArea.append("\n");
        }

    }

    private Protein getTOPSdiag(String diagram_id, String magic)
            throws MalformedURLException, IOException {

        Protein p = null;

        StringBuffer topsfile_url_sb = new StringBuffer(ResultsApp.TopsFileURLbase);
        topsfile_url_sb.append(magic);
        topsfile_url_sb.append("/");
        topsfile_url_sb.append(diagram_id);
        topsfile_url_sb.append(".tops");

        URL topsfile_url = new URL(topsfile_url_sb.toString());
        InputStream tis = topsfile_url.openStream();
        BufferedReader br = new BufferedReader(new InputStreamReader(tis));
        p = new Protein(br);

        return p;

    }

    private String getTOPSstatus(String diagram_id, String magic)
            throws MalformedURLException, IOException {

        StringBuffer topsfile_url_sb = new StringBuffer(ResultsApp.TopsFileURLbase);
        topsfile_url_sb.append(magic);
        topsfile_url_sb.append("/");
        topsfile_url_sb.append("status");

        URL topsfile_url = new URL(topsfile_url_sb.toString());
        InputStream tis = topsfile_url.openStream();
        BufferedReader br = new BufferedReader(new InputStreamReader(tis));

        return br.readLine();

    }

}
